---
deployment:
  tasks:
    - export DEPLOYPATH=/home/baikiesc/proto.baikieschipshop/
    - index.html $DEPLOYPATH
    - about-us.html $DEPLOYPATH
    - /images/ -R images $DEPLOYPATH
    - /assets/ -R assets $DEPLOYPATH
    - /css/ -R css $DEPLOYPATH
    - /fonts/ -R fonts $DEPLOYPATH
    - /js/ -R js $DEPLOYPATH
    - /vendour/ -R vendour $DEPLOYPATH